services:
  web:
    build: .
    ports:
      - "5013:5000"
    volumes:
      - ./usuarios.json:/app/usuarios.json
    restart: unless-stopped
    environment:
      - GUNICORN_WORKERS=3
      - GUNICORN_THREADS=2